# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 861c4cd9b1aa70abb1b6126baf12912be7260637801f7266af1b4423c52bbb461f3dc389d7b6d32a4db17c2f2c79947cd88f2eef778df253da6675898ae6f3d5

test:
  secret_key_base: f22f3e45f7b57c86b656430c66581e5ecd5b41c1166fe8c793e09f143f0f1e982b63eae8a4aa7c69488d206428cdaff5c2c35090f858c1bb840cbf738ea7c1d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
